#Clock signal
set_property PACKAGE_PIN W5 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports Clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {passwordEntered[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered[0]}]
set_property PACKAGE_PIN V16 [get_ports {passwordEntered[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered[1]}]
set_property PACKAGE_PIN W16 [get_ports {passwordEntered[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered[2]}]
set_property PACKAGE_PIN W17 [get_ports {passwordEntered[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered[3]}]
set_property PACKAGE_PIN W15 [get_ports {passwordEntered2[0]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered2[0]}]
set_property PACKAGE_PIN V15 [get_ports {passwordEntered2[1]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered2[1]}]
set_property PACKAGE_PIN W14 [get_ports {passwordEntered2[2]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered2[2]}]
set_property PACKAGE_PIN W13 [get_ports {passwordEntered2[3]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {passwordEntered2[3]}]
set_property PACKAGE_PIN U1 [get_ports {sensorExit}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensorExit}]
set_property PACKAGE_PIN T1 [get_ports {sensorEntrance}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensorEntrance}]
set_property PACKAGE_PIN R2 [get_ports {Rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {Rst}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {pass[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pass[0]}]
set_property PACKAGE_PIN E19 [get_ports {pass[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pass[1]}]
set_property PACKAGE_PIN U19 [get_ports {pass[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pass[2]}]
set_property PACKAGE_PIN V19 [get_ports {pass[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pass[3]}]
set_property PACKAGE_PIN W18 [get_ports {pass2[0]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {pass2[0]}]
set_property PACKAGE_PIN U15 [get_ports {pass2[1]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {pass2[1]}]
set_property PACKAGE_PIN U14 [get_ports {pass2[2]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {pass2[2]}]
set_property PACKAGE_PIN V14 [get_ports {pass2[3]}]               	 
set_property IOSTANDARD LVCMOS33 [get_ports {pass2[3]}]
set_property PACKAGE_PIN U3 [get_ports {redLed}]
set_property IOSTANDARD LVCMOS33 [get_ports {redLed}]
set_property PACKAGE_PIN P3 [get_ports {greenLed}]
set_property IOSTANDARD LVCMOS33 [get_ports {greenLed}]
set_property PACKAGE_PIN N3 [get_ports {senEx}]
set_property IOSTANDARD LVCMOS33 [get_ports {senEx}]
set_property PACKAGE_PIN P1 [get_ports {senEnt}]
set_property IOSTANDARD LVCMOS33 [get_ports {senEnt}]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property PACKAGE_PIN W6 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN U8 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN V8 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN U5 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN V5 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN U7 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]

set_property PACKAGE_PIN U2 [get_ports {anodeActivate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeActivate[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodeActivate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeActivate[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodeActivate[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeActivate[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodeActivate[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeActivate[3]}]
